from django.urls import path
from . import views

urlpatterns = [
    path('', views.cargarInicio, name='inicio'),
    path('AddProduct', views.cAddProd),
    path('search/', views.buscar_productos, name='buscar_productos'),
    path('edProd/<id>', views.cEdProd),
    path('Prodview/<id>', views.cProdview ),
    path('addPro', views.addProd),
    path('adminView', views.cadmStore),
    path('eddCate', views.editCate),
    path('edCate/<id>', views.cEdCate),
    path('Catelist', views.cCatelist),
    path('Cateview/<id>', views.cCates),
    path('Prodlist', views.listProd),
    path('delProd/<id>', views.delProduct),
    path('delUser/<username>', views.delUser),
    path('eddProd', views.editProd),
    path('obtainProd', views.obInfProd),
    path('obtainUser', views.obInfUser),
    path('obtainCate', views.obInfCate),
    path('login', views.cLogin, name='login'),
    path('register', views.cRegister),
    path('contact', views.cContact),
    path('logout', views.logout_view),
    path('userlist', views.cUserlist, name="ListaUsuarios"),
    path('categories', views.cCategories),
    path('edUser/<username>', views.cedUser),
    path('eddUser', views.editUser),
    path('AddCateg', views.cAddCate),
    path('addCate', views.addCate),
    path('delCate/<id>', views.delCate),
    path('eddAcc', views.editData),
    path('edAcc/<username>', views.cedAcc),
    path('cMyAcc', views.cmyAcc),
    path('eddCon', views.editPass),
    path('edCon/<username>', views.cEditPass),
    path('cdelAcc/<username>', views.cdelAcc),
    path('delAcc', views.delAcc),
    path('ccart', views.cCarrito),
    path('descuento-stock', views.descuento_stock, name='descuento_stock'),
]
