# Generated by Django 4.2.2 on 2023-06-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_product_price_alter_product_stock_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
