# Generated by Django 4.2.2 on 2023-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_img',
            field=models.ImageField(default='none', upload_to='CateImg'),
            preserve_default=False,
        ),
    ]
